name: assets_audio_player
description: Play music/audio stored in assets files directly from Flutter & Network, Radio, LiveStream, Local files. Compatible with Android, iOS, web and MacOs
version: 2.0.9+2

#author: Florent Champigny <champigny.florent@gmail.com>
homepage: https://github.com/florent37/Flutter-AssetsAudioPlayer

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
      sdk: flutter
  rxdart: ^0.24.1
  uuid: ^2.0.4
  http: ^0.12.1 #to download / cache network files
  path_provider: ^1.6.8 # removed this because it cancel flutter/android/ios on pub.dev path_provider: ^1.6.10


  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  assets_audio_player_web: ^2.0.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.github.florent37.assets_audio_player
        pluginClass: AssetsAudioPlayerPlugin
        mainClass: AssetsAudioPlayerPlugin
      ios:
        pluginClass: AssetsAudioPlayerPlugin
      macos:
        pluginClass: AssetsAudioPlayerPlugin
      web:
        default_package: assets_audio_player_web
      # moved to assets_audio_player_web
      #web:
      #  pluginClass: AssetsAudioPlayerPlugin
      #  fileName: assets_audio_player_web.dart
